# Generated by Django 4.2.11 on 2024-03-05 11:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=20)),
                ('noOfRooms', models.BigIntegerField()),
                ('bedrooms', models.BigIntegerField()),
                ('bathrooms', models.BigIntegerField()),
                ('roomFloor', models.BigIntegerField()),
                ('TotalFloor', models.BigIntegerField()),
                ('image', models.ImageField(default='bg1.jpg', upload_to='images')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')])),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingManager',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.registration')),
                ('employee_id', models.CharField(max_length=10)),
                ('image', models.ImageField(default='avator.jpg', upload_to='images')),
            ],
            bases=('app1.registration',),
        ),
    ]
