# Generated by Django 5.0.2 on 2024-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('status', models.BooleanField()),
                ('noOfRooms', models.BigIntegerField()),
                ('bedrooms', models.BigIntegerField()),
                ('bathrooms', models.BigIntegerField()),
                ('roomFloor', models.BigIntegerField()),
                ('TotalFloor', models.BigIntegerField()),
            ],
        ),
    ]
