# Generated by Django 5.0.2 on 2024-03-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='address',
            new_name='area',
        ),
    ]
