# Generated by Django 5.0.2 on 2024-02-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='bg1.jpg', upload_to='images'),
        ),
    ]
