# Generated by Django 5.0.2 on 2024-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_address_properties_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='country',
            field=models.CharField(default='Default Country', max_length=100),
        ),
    ]
