# Generated by Django 4.2.11 on 2024-03-07 07:44

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_properties_city_properties_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='TotalFloor',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='area',
            field=models.CharField(choices=[('22 Mazoria', '22 Mazoria'), ('Atlas', 'Atlas'), ('Ayat site', 'Ayat site'), ('CMC site', 'CMC site')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bathrooms',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedrooms',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_city', message='City name should contain only alphabetic characters.', regex=re.compile('^[A-Za-z\\s]+$'))]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_country', message='Country name should contain only alphabetic characters.', regex=re.compile('^[A-Za-z\\s]+$'))]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='noOfRooms',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='propertyType',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='roomFloor',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
