# Generated by Django 5.0.2 on 2024-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_properties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='bg1.jpg', upload_to='imagess'),
        ),
    ]
