# Generated by Django 4.2.11 on 2024-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_properties_totalfloor_alter_properties_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('admin', 'Admin'), ('salesperson', 'Salesperson'), ('marketing_manager', 'Marketing Manager'), ('maintenance_staff', 'Maintenance Staff')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
