# Generated by Django 5.0.2 on 2024-02-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_properties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=20),
        ),
    ]
