# Generated by Django 5.0.2 on 2024-02-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_properties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='size',
            field=models.FloatField(),
        ),
    ]
