# Generated by Django 5.0.2 on 2024-03-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_registration_role_alter_registration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.registration')),
                ('img', models.ImageField(upload_to='employee_images')),
                ('empID', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('app1.registration',),
        ),
    ]
