# Generated by Django 5.0.2 on 2024-02-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_properties_price_alter_properties_size'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='properties',
            table='properties',
        ),
    ]
