# Generated by Django 5.0.2 on 2024-03-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empID',
        ),
        migrations.RemoveField(
            model_name='marketingmanager',
            name='employee_id',
        ),
    ]
