# Generated by Django 5.0.2 on 2024-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_properties_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='bg1.jpg', upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='properties',
            table=None,
        ),
    ]
