# Generated by Django 5.0.2 on 2024-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_employee_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
