# Generated by Django 5.0.2 on 2024-03-02 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_properties_image_alter_properties_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
