# Generated by Django 5.0.2 on 2024-03-04 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_properties_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingManager',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.registration')),
                ('employee_id', models.CharField(max_length=10)),
            ],
            bases=('app1.registration',),
        ),
    ]
