# Generated by Django 5.0.2 on 2024-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_properties_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('role', models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('partner_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('partner_work_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
