# Generated by Django 5.0.2 on 2024-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_marketingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmanager',
            name='image',
            field=models.ImageField(default='avator.jpg', upload_to='images'),
        ),
    ]
