# Generated by Django 5.0.2 on 2024-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
