# Generated by Django 5.0.2 on 2024-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_application_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='partner_phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
