# Generated by Django 5.0.2 on 2024-03-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_employee_img'),
        ('app1', '0012_alter_application_age_and_more'),
    ]

    operations = [
    ]
