# Generated by Django 5.0.2 on 2024-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_merge_20240314_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('building_number', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('type_of_maintenance', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='age',
            new_name='work_status',
        ),
    ]
