# Generated by Django 5.0.2 on 2024-03-22 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_maintenance_rename_age_application_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
