# Generated by Django 5.0.2 on 2024-03-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_contactmessage'),
        ('app1', '0015_application_date_added'),
    ]

    operations = [
    ]
