# Generated by Django 5.0.2 on 2024-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_contactmessage_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='lawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
