# Generated by Django 5.0.2 on 2024-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_contactmessage_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('building_number', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('floor_number', models.CharField(max_length=100)),
                ('type_of_maintenance', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('notstart', 'Not Started'), ('inprogress', 'In Progress'), ('complete', 'Complete')], default='notstart', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
