# Generated by Django 5.0.2 on 2024-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_properties_air_conditioning_properties_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='propertyType',
            field=models.CharField(choices=[('Commercial Apartment', 'Commercial Apartment'), ('Residential Apartment', 'Residential Apartment')], max_length=100),
        ),
    ]
