# Generated by Django 5.0.2 on 2024-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_properties_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='add_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
