# Generated by Django 5.0.2 on 2024-03-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='role',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type_of_maintenance',
            field=models.CharField(max_length=20),
        ),
    ]
