# Generated by Django 5.0.2 on 2024-03-27 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_application_role_remove_workorder_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicationrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('work_status', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
