# Generated by Django 5.0.2 on 2024-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_properties_add_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='add_map',
        ),
        migrations.AlterField(
            model_name='properties',
            name='propertyType',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential Apartment', 'Residential Apartment')], max_length=100),
        ),
    ]
