# Generated by Django 5.0.2 on 2024-03-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_applicationrent'),
        ('app1', '0021_remove_properties_add_map_and_more'),
    ]

    operations = [
    ]
