# Generated by Django 4.2.11 on 2024-03-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_applicationrent'),
        ('app1', '0021_remove_properties_add_map_and_more'),
    ]

    operations = [
    ]
