# Generated by Django 5.0.2 on 2024-03-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_merge_20240327_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='maintenance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.maintenance'),
        ),
    ]
