# Generated by Django 5.0.2 on 2024-03-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_merge_20240327_2139'),
        ('app1', '0022_merge_20240327_2305'),
    ]

    operations = [
    ]
