# Generated by Django 5.0.2 on 2024-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_merge_20240328_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='properties',
            name='propertyType',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=100),
        ),
    ]
