# Generated by Django 5.0.2 on 2024-04-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_report_delete_workorder_maintenance_sent_status_and_more'),
        ('app1', '0024_remove_properties_date_added_and_more'),
    ]

    operations = [
    ]
