# Generated by Django 4.2.11 on 2024-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_employee_is_active_registration_is_active'),
        ('app1', '0025_merge_20240401_1011'),
    ]

    operations = [
    ]
