# Generated by Django 4.2.11 on 2024-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_merge_20240401_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Rented', 'Rented'), ('Soled', 'Soled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('admin', 'Admin'), ('finace', 'finace'), ('salesperson', 'Salesperson'), ('marketing_manager', 'Marketing Manager'), ('maintenance_staff', 'Maintenance Staff')], default='customer', max_length=20),
        ),
    ]
