# Generated by Django 5.0.2 on 2024-04-26 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_finance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='applicationrent',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='applicationrent',
            old_name='nationality',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='property_id',
        ),
        migrations.AddField(
            model_name='application',
            name='kebele',
            field=models.CharField(default='Kebele', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(default='middle name', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application_sale', to='app1.properties'),
        ),
        migrations.AddField(
            model_name='application',
            name='sub_city',
            field=models.CharField(default='sub city', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationrent',
            name='kebele',
            field=models.CharField(default='Kebele', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationrent',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='app1.properties'),
        ),
        migrations.AddField(
            model_name='applicationrent',
            name='sub_city',
            field=models.CharField(default='sub city', max_length=200),
        ),
        migrations.AddField(
            model_name='finance',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Finance', to='app1.properties'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
