# Generated by Django 5.0.2 on 2024-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
