# Generated by Django 5.0.2 on 2024-04-27 16:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_application_date_added_alter_application_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_city_name', message='City name can only contain letters.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='sub_city',
            field=models.CharField(default='sub city', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_sub_city_name', message='Sub City name can only contain letters.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
