# Generated by Django 5.0.2 on 2024-04-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_application_date_added_alter_application_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_added',
        ),
    ]
