# Generated by Django 5.0.2 on 2024-04-27 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_application_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
