# Generated by Django 5.0.3 on 2024-05-06 09:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_application_email_alter_applicationrent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='app1.properties'),
        ),
        migrations.CreateModel(
            name='AskMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('emoloyee_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance_employee', to='app1.employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance', to='app1.properties')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance_registration', to='app1.registration')),
            ],
        ),
    ]
