# Generated by Django 5.0.3 on 2024-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_finance_property_askmaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askmaintenance',
            name='emoloyee_email',
        ),
        migrations.AddField(
            model_name='askmaintenance',
            name='employee_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
