# Generated by Django 5.0.3 on 2024-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_askmaintenance_emoloyee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askmaintenance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='askmaintenance',
            name='employee_email',
        ),
        migrations.AddField(
            model_name='askmaintenance',
            name='service',
            field=models.CharField(choices=[('Electrical Maintenance:', 'Electrical Maintenance:'), ('Plumbing Maintenance', 'Plumbing Maintenance')], default='Electrical Maintenance', max_length=50),
        ),
    ]
