# Generated by Django 5.0.3 on 2024-05-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_remove_askmaintenance_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askmaintenance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance_employee', to='app1.employee'),
        ),
        migrations.AlterField(
            model_name='askmaintenance',
            name='service',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing')], default='Electrical Maintenance', max_length=50),
        ),
    ]
