# Generated by Django 5.0.3 on 2024-05-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_askmaintenance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askmaintenance',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance', to='app1.properties'),
        ),
        migrations.AlterField(
            model_name='askmaintenance',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='askmaintenance_registration', to='app1.registration'),
        ),
    ]
