# Generated by Django 5.0.3 on 2024-05-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_alter_askmaintenance_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('admin', 'Admin'), ('finace', 'finace'), ('salesperson', 'Salesperson'), ('marketing_manager', 'Marketing Manager'), ('maintenance_staff/electrician', 'Maintenance Staff/electrician'), ('maintenance_staff/plumber', 'Maintenance Staff/plumber')], default='customer', max_length=30),
        ),
    ]
