# Generated by Django 4.2.11 on 2024-05-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_alter_registration_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_markate', models.DateField()),
                ('property', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salespersons', to='app1.properties')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salespersons', to='app1.registration')),
            ],
        ),
    ]
